### ISSUE TITLE
Let's document: systemd

### ISSUE THREAD

**Issue by acuteenvy** [tldr-pages/tldr#10191]
https://systemd.io

## Commands:

- [x] bootctl → #5418
- [x] busctl → #10271
- [x] coredumpctl → #5421
- [x] homectl → #5688
- [x] hostnamectl → #1369
- [ ] importctl
- [x] journalctl → #113
- [x] kernel-install → #10919, #10923
- [x] localectl → #7272
- [x] loginctl → #9188
- [x] machinectl →#10920
- [x] mount.ddi **(symlink to `systemd-dissect`)** → #11622
- [x] networkctl → #10091
- [x] oomctl → #10107
- [x] portablectl → #11212
- [x] resolvectl → #7484
- [x] run0 → #13263
- [x] systemctl → #112
- [x] systemd-ac-power → #10196
- [x] systemd-analyze → #844
- [x] systemd-ask-password → #10824
- [x] systemd-cat → #10194
- [x] systemd-cgls→ #10933
- [x] systemd-cgtop →#10934
- [x] systemd-confext **(symlink to `systemd-sysext`)** → #11479
- [x] systemd-creds → #10936
- [x] systemd-cryptenroll → #10731
- [ ] systemd-cryptsetup 
- [x] systemd-delta → #10388
- [x] systemd-detect-virt → #10723
- [x] systemd-dissect → #11414
- [x] systemd-escape→#10937
- [x] systemd-firstboot → #10493
- [ ] systemd-home-fallback-shell
- [x] systemd-hwdb → #10510
- [x] systemd-id128 → #11514
- [x] systemd-inhibit → #10879
- [x] systemd-machine-id-setup → #11447
- [x] systemd-mount → #10509
- [x] systemd-notify → #10618
- [x] systemd-nspawn → #11358, #11398
- [x] systemd-path → #10622
- [x] systemd-repart→#10880
- [x] systemd-resolve **(symlink to `resolvectl`)** →  #11543
- [x] systemd-run → #9949
- [x] systemd-socket-activate → #11221
- [x] systemd-stdio-bridge → #11330
- [x] systemd-sysext → #10724 
- [x] systemd-sysusers → #10693
- [x] systemd-tmpfiles → #10670
- [x] systemd-tty-ask-password-agent → #10656
- [x] systemd-umount **(symlink to `systemd-mount`)** → #10509
- [x] timedatectl → #546
- [x] udevadm → #6478
- [x] userdbctl → #10662
- [ ] varlinkctl

**Comment by quantumflo** [comment]
Hi can this issue be assigned to me?

**Comment by kbdharun** [comment]
> Hi can this issue be assigned to me?

Assigned, Feel free to create PRs for the missing commands.

**Comment by quantumflo** [comment]
Added for systemd-notify

**Comment by RoepLuke** [comment]
PR for systemd-cryptenroll is Work in Progress. #10731 

Currently, there are well over 8 examples, so I need to remove many of them (and make some other changes to conform to the guidelines). However, I would be happy to get some opinions on which examples should be removed (or how to combine some of them) as I am not sure, I'll be able to get below about 10 or 12 without leaving relevant examples out. And I kind of don't think It should only be up to me to decide what examples TLDR wants to show for systemd-cryptenroll. Thank you very much.

**Comment by rothgar** [comment]
Are you still looking for help on these commands? I can add a few this week.

**Comment by kbdharun** [comment]
> Are you still looking for help on these commands? I can add a few this week.

Yes, feel free to work the commands that don't have open/merged PRs yet.

**Comment by sgrverma23** [comment]
PR for kernel-install: https://github.com/tldr-pages/tldr/pull/10919

**Comment by SAYUK09** [comment]
Document ` systemd-socket-activate`

Check it out: https://github.com/tldr-pages/tldr/pull/11221

**Comment by quantumflo** [comment]
Hi @kbdharun can you reassign as I have submitted a pull request

**Comment by quantumflo** [comment]
systemd-confext and systemd-sysext seems to be similar @kbdharun @gutjuri @sebastiaanspeck 
From the docs I see this
systemd-sysext  concept follows the same principle as the [systemd-sysext(1)](https://www.freedesktop.org/software/systemd/man/latest/systemd-sysext.html#) functionality but instead of working on /usr and /opt, confext will extend only /etc. Files and directories contained in the confext images outside of the /etc/ hierarchy are not merged, and hence have no effect when included in the image. Formats for these images are of the same as sysext images. The merged hierarchy will be mounted with "nosuid" and (if not disabled via --noexec=false) "noexec".

**Comment by quantumflo** [comment]
@kbdharun @gutjuri @sebastiaanspeck @acuteenvy 
Can we close this issue or does alias pages needs to be added for the ones that are having symlink but no page

**Comment by arpit1385** [comment]
Hi! I’d like to work on adding systemd-home-fallback-shell and  varlinkctl as part of Hacktoberfest.

**Comment by sebastiaanspeck** [comment]
> Hi! I’d like to work on adding systemd-home-fallback-shell and varlinkctl as part of Hacktoberfest.

Feel free to work on it and simply open a PR.
