### ISSUE TITLE
Let's document: Rust tools

### ISSUE THREAD

**Issue by acuteenvy** [tldr-pages/tldr#10630]
#### General commands
- [x] cargo → #869
- [x] cargo help → #10712
- [x] cargo version → #10712

#### Build commands
- [x] cargo bench → #10771
- [x] cargo build → #4302
- [x] cargo check → #10744
- [x] cargo clean → #10770
- [x] cargo clippy → #4316
- [x] cargo doc → #3697
- [x] cargo fetch → #10883
- [x] cargo fix → #10774 
- [x] cargo fmt → #10770
- [x] cargo run → #10795
- [x] cargo rustc → #4336
- [x] cargo rustdoc → #10828
- [x] cargo test → #4268
- [x] cargo report → #10798

#### Manifest commands
- [x] cargo add → #8246
- [x] cargo generate-lockfile → #10918
- [x] cargo locate-project → #10999
- [x] cargo metadata → #11114
- [x] cargo pkgid → #11349
- [x] cargo remove →#10816
- [x] cargo tree → #11349
- [x] cargo update → #10745
- [x] cargo vendor → #11349
- [x] cargo verify-project → #11349

#### Package commands
- [x] cargo init → #10742
- [x] cargo install → #11351
- [x] cargo new → #10742
- [x] cargo search → #11351
- [x] cargo uninstall → #11351

#### Publishing commands
- [x] cargo login → #11337
- [x] cargo logout → #10805
- [x] cargo owner → #11337
- [x] cargo package → #11337
- [x] cargo publish → #11337
- [x] cargo yank → #11337

### Rustdoc - https://doc.rust-lang.org/rustdoc
- [x] rustdoc → #10902

### Rustup - https://github.com/rust-lang/rustup
- [x] rustup → #1690
- [x] rustup show → #10642
- [x] rustup update → #10642
- [x] rustup install → #10661
- [x] rustup check → #10642
- [x] rustup default → #10642
- [x] rustup toolchain → #10642
- [x] rustup target → #10642
- [x] rustup component → #10729
- [x] rustup override → #10729
- [x] rustup run → #10661
- [x] rustup which → #10661
- [x] rustup doc → #10729
- [x] rustup man → #10661
- [x] rustup self → #10729
- [x] rustup set → #10729
- [x] rustup completions → #10729
- [x] rustup help → #10661

**Comment by Cioraz** [comment]
Hey!
I would like to work on this issue
