### ISSUE TITLE
Add missing English pages

### ISSUE THREAD

**Issue by sebastiaanspeck** [tldr-pages/tldr#11147]
Right now there are 19 pages that are translated to a different language than English, but the English page itself doesn't exist. When looking in-debt only 1 page is really missing in English. The other 18 are incorrect in path to the file.
This issue will list those pages and keeps track of the progress.

- [x] groupel (defined in pages.ca/linux/groupel.md) - this is a typo and should be renamed to groupdel.md &#8594; #11163
- [x] clamav (defined in pages.ca/linux/clamav.md and in pages.es/linux/clamav.md) - this one should be merged into pages.ca/common/clamav.md and pages.es/common/clamav.md &#8594; #11283
- [x] google-chrome.md (defined in pages.de/linux/google-chrome.md) - this one should be moved to pages.de/common/google-chrome.md to reflect the English translation &#8594; #11163
- [x] httpie (defined in pages.de/common/httpie.md) - this one should be moved to pages.de/linux/httpie.md and to #11163
- [x] warm (defined in pages.es/osx/warm.md) - this one should be renamed to pages.es/osx/warmd.md &#8594; #11163
- [x] chmod (defined in pages.es/linux/chmod.md) - this one should be moved to pages.es/common/chmod.md &#8594; #11163
- [x] where (defined in pages.fa/linux/where.md) - this one should be moved to pages.fa/windows/where.md and to pages.fa/common/where.md &#8594; #11163
- [x] powershell (defined in pages.fr/windows/poweshell.md and pages.zh/windows/powershell.md) - this one should be moved to pages.XX/common/powershell.md &#8594; #11264
- [x] ruget (defined in pages.hi/common/ruget.md) - this one should be moved to pages.hi/linux/ruget.md &#8594; #11163
- [x] hello (defined in pages.it/linux/windows.md) - this one should be moved to pages.it/common/hello.md &#8594; #11163
- [x] mv - (defined in pages.pt_BR/linux/mv.md) - this one should be moved to pages.pt_BR/common/mv.md &#8594; #11163
- [x] ls - (defined in pages.pt_BR/linux/ls.md) - this one should be moved to pages.pt_BR/common/ls.md &#8594; #11163
- [x] sudo - (defined in pages.pt_BR/linux/sudo.md) - this one should be moved to pages.pt_BR/common/sudo.md &#8594; #11163
- [x] krita - (defined in pages.ru/linux/krita.md) - this one should be moved to pages.ru/common/krita.md &#8594; #11163
- [x] popd - (defined in pages.zh/osx/popd.md) - this one should be moved to pages.zh/common/popd.md) &#8594; #11253
- [x] pushd - (defined in pages.zh/osx/pushd.md) - this one should be moved to pages.zh/common/pushd.md) &#8594; #11253
- [x] oathtool - (defined in pages.zh/osx/oathtool.md) - this one should be moved to pages.zh/common/oathtool.md) &#8594; #11253
- [x] htpasswd - (defined in pages.ko/linux/htpasswd.md) - this one should be moved to pages.ko/common/htpasswd.md) &#8594; #11271
- [x] esbuild - (defined in pages.ko/linux/esbuild.md) - this one should be moved to pages.ko/common/esbuild.md) &#8594; #11281

**Comment by Magrid0** [comment]
I'm not sure if I understood correctly but I'll try to work on this in a while as soon as I have some spare time

**Comment by Magrid0** [comment]
@sebastiaanspeck groupel seems to be a typo, the right command is groupdel and is already present in english

**Comment by Magrid0** [comment]
> are the open items clear enough for you?

~~Sorry I haven't looked at them yet~~
Everything's clear except `clamav`

**Comment by Magrid0** [comment]
> I have updated `clamav` to make it more clear! Please let me know if it is still unclear

got it

**Comment by deadpyxel** [comment]
I can probably take care of `powershell` if there's nothing in progress, I am trying to understand the `clamav` merge.

**Comment by deadpyxel** [comment]
So, about the `where` command, I saw that a PR was closed related to it. Should I just go head and create a new one or is it better to wait for the original authors?

**Comment by deadpyxel** [comment]
Never mind, I just finished reading the conversation history.

**Comment by Magrid0** [comment]
@sebastiaanspeck  With clamav I have to copy the examples in /linux to /common right?

**Comment by Magrid0** [comment]
also htpasswd.md doesn't exist in pages.ko

**Comment by Magrid0** [comment]
> It does: https://github.com/tldr-pages/tldr/blob/main/pages.ko/linux/htpasswd.md

weird, I just cloned the repository 15 minutes ago and I don't have it... I'll try to clone again

**Comment by IMHOJEONG** [comment]
The file location of htpasswd.md in pages.ko/linux was changed to pages.ko/common.

**Comment by Magrid0** [comment]
Can this issue be closed? @sebastiaanspeck
