### ISSUE TITLE
Tracker issue: 2023

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#11146]
## Documenting Progress

This checklist was moved from #10755 (as suggested by @sebastiaanspeck).

### Section 1: Main repo and Org

----

#### To update

> [!NOTE]
> To avoid merge conflicts, if there is an open PR updating the style guide, it is recommended to wait for it to get merged before creating a new one.

- [x] **Style guide**
    - [x] Add clear information about more information links (and what URLs should be used for translation pages) →#11320
    - [x] Add information to not localize Microsoft Learn URLs [_Existing informal rule_] → #11320 
    - [x] Document `Display help` and `Display version` generic term preference and order. [_Existing informal rule_] → #11854 
    - [x] Document usage of mnemonics → #11619
    - [x] Document Windows and PowerShell specific rules → #11619
    - [x] Document how multiple examples can be concatenated and separated with `|` [_Existing informal rule_] (Already present, the wording was improved)
    - [x] Document Capitalizing Brand names/Project names in applicable places and enclosing package names inside backticks. [_Existing informal rule_] (Partially done) → #11860
    - [x] Document enclosing links inside angular brackets. [_Existing informal rule_] → #11320
    - [x] Document how to handle passing arguments → #10906
    - [x] Document we prefer long options, see #8304 (with exceptions for some pages) [_Existing informal rule_]  → #11619
    - [x] Document not specifying the platform/CLI in the page descriptions. Only encourage it for GUI applications. [_Existing informal rule_] → #10858
    - [x] Document preferring `stdout` over standard output [_Existing informal rule_] → #11196
    - [x] Document highlighting file names [_Existing informal rule_] → #10858
    - [x] Document wrapping file extensions in ~Quotes~ Backticks (Ref. #10868) → #10858
    - [x] Document preference for non-versioned links. (i.e `latest` or none) →#11320
    - [x] Document requirement for spacing on French pages [_Existing informal rule_] → #11860
    - [x] Document requirement to not translate acronyms → #11860
    - [x] Document page heading to be kept as the command name [_Existing informal rule_] (except when it starts with a symbol) → #11860
    - [x] Document how to highlight keycaps → #11860

- [x]  **Contributing guide**
   - [x] Document suggestion to enable check for allowing MAINTAINERS to edit PRs [_Existing informal rule_] → #11669
   - [x] Document how to seamlessly add a new language to tldr and which files to prefill for translation templates → #11669
   - [x] Document that translations must be done based on the English page → #11669
   - [x] Document how to test pages locally using `tldr-lint` before creating a PR → #11669
   - [x] Document how to batch suggestions and make a single commit → #11669
   - [x] Add more commit examples  → #11669
   - [x]  Document how to run the test script to reformat code for Black style, etc → #11669
   - [x] Document how to handle name collisions with files →  #11861
   - [x] Add suggestion that when typo fixes are done by native speakers (they must update the page if it's outdated too) → #11861
   - [x] Document that you can use the main page of a tool/utility to reference subcommands tldr pages → #11861

- [x] **Scripts directory**
   - [x] Document what each script does → #11810

- [x] **PR template**
  - [x] ~Add comment highlighting running tldr-lint locally or explaining the PR would go through tldr-bot running the same~ →  #11671 (Proposal dropped)

- [x] **Client Specification**
  - [x] Document to escape the placeholder syntax  → #10730
  - [x] Add suggestion that clients should detect platforms in the pages directory automatically → #11523 

- [x] **MAINTAINERS guide**
  - [x] Add a section about transparency and minimum time before taking over the PR → #10818
  - [x] Document preference to include the coauthored part in the commit message for non-trivial PRs → #11862
  - [x] Document preference to use "decision" label for PRs that need discussion (and shouldn't be merged) → #11862
  - [x] Remove minimum time to wait before merging PR requirement → #11391
  - [x] Add suggested time requirement for new additions → #11862
  - [x] Add documentation on handling failing actions/workflows and waiting for CLA checks →#11862
  - [x] ~Add "platform addition consideration section" to document notability criteria (i.e should have a stable release, etc) for adding a new platform~ → Dropped this as we rarely add new platforms and the addition must be discussed with the maintainers in the chatroom then and there (and a general guideline would be too restrictive).

- [x] **Community roles**
  - [x] Document the CODEOWNERS file and procedure to add yourself (maintainers) to it → #11646

----

#### To create

- [x] Issue template
   - [x] Page modification template → #10826
   - [x] Let's Document template → #11326

----

#### Others

**Platform Additions**

- [x] Add support for OpenBSD platform → #10698
- [x] Add OpenBSD support to the Web client → https://github.com/InBrowserApp/tldr.inbrowser.app/pull/18
- [x] Add support for FreeBSD and NetBSD platforms→ #11313
- [x] Add FreeBSD support to the Web client → https://github.com/InBrowserApp/tldr.inbrowser.app/pull/19

----

**Miscellaneous**

- [ ] Standardize scripts to follow a uniform convention (Ref. https://github.com/tldr-pages/tldr/pull/11836#issue-2055773169) →
- [x] Build and deploy tldr book PDF for translations → #10846
- [x] Deprecation of language team in favor of CODEOWNERS file  → #11188
- [x] Standardize Repo and Security settings throughout the Org → #11187
- [x] Remove unused webhooks and applications → #11153, #11157
- [x] Set `main` as the default branch for all Repos
- [x] Add branch protection rule for all repos (except `tlrc` and `tldr-translation-pairs-gen`) → #10830, #10831, #10832, #10833
- [x] Add support for generating PDFs for specific platforms → #11195
- [x] ~Run scripts and add standard (alias page) and more information link translation~ → #11331
- [x] Revert standard translation script commit →  #11374

----

### Section 2: tlrc

- [x] Addition of new official client written in Rust (`tlrc`)
- [x] Add `tlrc` to Winget → https://github.com/microsoft/winget-pkgs/pull/123733
- [x] Add `tlrc` to Homebrew → https://github.com/Homebrew/homebrew-core/pull/152996
- [x] Replace C client with `tlrc` in Wiki
- [x] Replace C client with `tlrc` in README →#11369

**Comment by kbdharun** [comment]
Yep, that seems to be the case. While creating a PR we can mention it too.

**Comment by kbdharun** [comment]
> Regarding the contributing guide: we could mention that one can run the linter locally.
> 
> Imo this would then close #4986.

Agreed, I have some free time today, will work on this.
