### ISSUE TITLE
Let's document: gcloud

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#11394]
## Command description

`gcloud` is a command-line tool for the Google Cloud Platform. Google Cloud Platform is a suite of cloud computing services that includes computing, data storage, data analytics, and machine learning.

Currently, we have only a single page for [`gcloud`](https://github.com/tldr-pages/tldr/blob/main/pages/common/gcloud.md) which covers very few commands and misses a lot of essential ones.

We can create new pages for all the associated subcommands and reference them using the Subcommand mention template on the current page. (Ref. #11387)

## Documentation

https://cloud.google.com/sdk/gcloud/reference

> [!NOTE]
> The cheatsheet links in the respective commands below are purely for reference to create a tldr page, for more information link use the above man page link for your respective command instead. And your page's name and title must match with the command/subcommand name.

## Platform

Common

### Basic commands (Getting Started)

- [x] [gcloud init](https://cloud.google.com/sdk/gcloud/reference/init) → #11626
- [x] [gcloud version](https://cloud.google.com/sdk/gcloud/reference/version) →#11647
- [x] [gcloud components install](https://cloud.google.com/sdk/gcloud/reference/components/install) → #11679
- [x] [gcloud components update](https://cloud.google.com/sdk/gcloud/reference/components/update) → #11682
- [x] [gcloud config set](https://cloud.google.com/sdk/gcloud/reference/config/set) → #11679
- [x] [gcloud info](https://cloud.google.com/sdk/gcloud/reference/info) → #11690

### Help

- [x] [gcloud help](https://cloud.google.com/sdk/gcloud/reference/help) →#11625
- [x] [gcloud feedback](https://cloud.google.com/sdk/gcloud/reference/feedback) →#11625
- [x] [gcloud topic](https://cloud.google.com/sdk/gcloud/reference/topic) →#11625

### Personalization (`config`)

Make the `gcloud` CLI your own; personalize your configuration with properties.

- [x] [gcloud config set](https://cloud.google.com/sdk/gcloud/reference/config/set) →#11625 #11679
- [x] [gcloud config get](https://cloud.google.com/sdk/gcloud/reference/config/get) →#11625
- [x] [gcloud config list](https://cloud.google.com/sdk/gcloud/reference/config/list) →#11625
- [x] [gcloud config configurations create](https://cloud.google.com/sdk/gcloud/reference/config/configurations/create) →#11625
- [x] [gcloud config configurations list](https://cloud.google.com/sdk/gcloud/reference/config/configurations/list) →#11625
- [x] [gcloud config configurations activate](https://cloud.google.com/sdk/gcloud/reference/config/configurations/activate) →#11625

### Authorization and Credentials

Grant and revoke authorization to the `gcloud` CLI and manage credentials.

- [x] [gcloud auth login](https://cloud.google.com/sdk/gcloud/reference/auth/login) → #11625
- [x] [gcloud auth activate-service-account](https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account) → #11625
- [x] [gcloud auth application-default](https://cloud.google.com/sdk/gcloud/reference/auth/application-default) → #11625
- [x] [gcloud auth list](https://cloud.google.com/sdk/gcloud/reference/auth/list) → #11625
- [x] [gcloud auth print-access-token](https://cloud.google.com/sdk/gcloud/reference/auth/print-access-token) → #11625
- [x] [gcloud auth revoke](https://cloud.google.com/sdk/gcloud/reference/auth/revoke) → #11625

### Projects

Manage project access policies.

- [x] [gcloud projects describe](https://cloud.google.com/sdk/gcloud/reference/projects/describe) → #11625
- [x] [gcloud projects add-iam-policy-binding](https://cloud.google.com/sdk/gcloud/reference/projects/add-iam-policy-binding) → #11625

### IAM

Configuring Identity and Access Management (IAM) preferences and service accounts.

- [x] [gcloud iam list-grantable-roles](https://cloud.google.com/sdk/gcloud/reference/iam/list-grantable-roles) → #11625
- [x] [gcloud iam roles create](https://cloud.google.com/sdk/gcloud/reference/iam/roles/create) →#11625
- [x] [gcloud iam service-accounts create](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/create) → #11625
- [x] [gcloud iam service-accounts add-iam-policy-binding](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/add-iam-policy-binding) → #11625
- [x] [gcloud iam service-accounts set-iam-policy-binding](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/set-iam-policy) →#11625
- [x] [gcloud iam service-accounts keys list](https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/list) →#11625

### Docker & Google Kubernetes Engine (GKE)

Manage containerized applications on Kubernetes.

- [x] [gcloud auth configure-docker](https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker) →#11625
- [x] [gcloud container clusters create](https://cloud.google.com/sdk/gcloud/reference/container/clusters/create) →#11625
- [x] [gcloud container clusters list](https://cloud.google.com/sdk/gcloud/reference/container/clusters/list) →#11625
- [x] [gcloud container clusters get-credentials](https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials) →#11625
- [x] [gcloud container images list-tags](https://cloud.google.com/sdk/gcloud/reference/container/images/list-tags) →#11625

### Virtual Machines & Compute Engine

Create, run, and manage VMs on Google Cloud infrastructure.

- [x] [gcloud compute zones list](https://cloud.google.com/sdk/gcloud/reference/compute/zones/list) →#11625
- [x] [gcloud compute instances create](https://cloud.google.com/sdk/gcloud/reference/compute/instances/create) →#11625
- [x] [gcloud compute instances describe](https://cloud.google.com/sdk/gcloud/reference/compute/instances/describe) →#11625
- [x] [gcloud compute instances list](https://cloud.google.com/sdk/gcloud/reference/compute/instances/list) →#11625
- [x] [gcloud compute disks snapshot](https://cloud.google.com/sdk/gcloud/reference/compute/disks/snapshot) →#11625
- [x] [gcloud compute snapshots describe](https://cloud.google.com/sdk/gcloud/reference/compute/snapshots/describe) →#11625
- [x] [gcloud compute snapshots delete](https://cloud.google.com/sdk/gcloud/reference/compute/snapshots/delete) →#11625
- [x] [gcloud compute ssh](https://cloud.google.com/sdk/gcloud/reference/compute/ssh) →#11625

### Serverless & App Engine

Build highly scalable applications on a fully managed serverless platform

- [x] [gcloud app deploy](https://cloud.google.com/sdk/gcloud/reference/app/deploy) →#11625
- [x] [gcloud app versions list](https://cloud.google.com/sdk/gcloud/reference/app/versions/list) →#11625
- [x] [gcloud app browse](https://cloud.google.com/sdk/gcloud/reference/app/browse) →#11625
- [x] [gcloud app create](https://cloud.google.com/sdk/gcloud/reference/app/create) →#11625
- [x] [gcloud app logs read](https://cloud.google.com/sdk/gcloud/reference/app/logs/read) →#11625

### Miscellaneous

- [x] [gcloud kms decrypt](https://cloud.google.com/sdk/gcloud/reference/kms/decrypt) → #11689
- [x] [gcloud logging logs list](https://cloud.google.com/sdk/gcloud/reference/logging/logs/list) → #11695 
- [x] [gcloud sql backups describe](https://cloud.google.com/sdk/gcloud/reference/sql/backups/describe) → #11722
- [x] [gcloud sql export sql](https://cloud.google.com/sdk/gcloud/reference/sql/export/sql) → #11695 

> [!NOTE]
> Some commands aren't listed in this list, feel free to create a page for them too, if you use it actively. (While #11625, adds common pages for the commands it is suggested to create separate pages for the subcommands too)

**Comment by FarhadK2022** [comment]
Hi @kbdharun , can you assign this to me please? Also, are you looking to add all of the links listed above to the project you have linked in you description? Any other links to documentation you are looking to add for gcloud?

**Comment by kbdharun** [comment]
> Also, are you looking to add all of the links listed above to the project you have linked in you description? Any other links to documentation you are looking to add for gcloud?

Yep, you can add pages for the listed subcommands (the cheatsheet links for each command would be a more than sufficient resource to cover the general usage).

**Comment by sbrl** [comment]
@FarhadK2022: No need to be assigned on issues like this to work on them :-) This issue is basically here to focus efforts of the community, since given the number of subcommands it's a lot of effort to document all of them.

Note that we would request that you don't open a single pull request with * all * of the pages in this issue, as that would be a lot of work to review! Instead, try and keep it to ~5 pages per PR at most, and preferably 1-2 pages in the first PR.

Many thanks for helping out!

**Comment by gutjuri** [comment]
Mentioning  #11625
