### ISSUE TITLE
Update to tldr-lint v0.0.9

### ISSUE THREAD

**Issue by owenvoke** [tldr-pages/tldr#5046]
We currently can't update as we need to clean up some of the pages. The new release now does the following:
- Validates the spelling of "More information: " (`TLDR016`)
- Validates that the URL uses angle brackets (`TLDR017`)
- Validates that there is only a single link per page (`TLDR018`)
- Validates that there are a maximum of 8 examples per page (`TLDR019`)

Currently when running `tldr-lint pages/`, it returns the following which needs to be resolved:

<details>
<summary>List of pages that need to be addressed</summary>

```text
pages/common/arc.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/deemix.md:5: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/eva.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/fnm.md:5: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/glow.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/glow.md:4: TLDR017 Information link should be surrounded with angle brackets
pages/common/ipython.md:4: TLDR017 Information link should be surrounded with angle brackets
pages/common/jq.md:0: TLDR019 Page should only include a maximum of 8 examples
pages/common/kotlin.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/nativefier.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/nc.md:0: TLDR019 Page should only include a maximum of 8 examples
pages/common/nmap.md:0: TLDR019 Page should only include a maximum of 8 examples
pages/common/notmuch.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/common/tar.md:0: TLDR019 Page should only include a maximum of 8 examples
Error: Parse error on line 5:
...irshcmdref.html>.> NOTE: 'guest_id' can...
----------------------^
Expecting 'INFORMATION_LINK', got 'DESCRIPTION_LINE'
pages/linux/efibootmgr.md:4: TLDR017 Information link should be surrounded with angle brackets
pages/linux/homeshick.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/linux/netselect.md:4: TLDR004 Command descriptions should end in a period
pages/linux/rofi.md:4: TLDR016 Label for information link should be spelled exactly `More information: `
pages/linux/vgs.md:4: TLDR017 Information link should be surrounded with angle brackets
pages/linux/yetris.md:0: TLDR019 Page should only include a maximum of 8 examples
pages/osx/brew.md:0: TLDR019 Page should only include a maximum of 8 examples
pages/windows/choice.md:5: TLDR016 Label for information link should be spelled exactly `More information: `
pages/windows/shutdown.md:0: TLDR019 Page should only include a maximum of 8 examples
```

</details>

https://github.com/tldr-pages/tldr/pull/5050 resolves most of these, and then the only other thing would be to decide what to do with the pages that are over the 8-example limit (`TLDR019`). These are the following:

- [x] `pages/common/jq.md` (#5057)
- [x] `pages/common/nc.md` (#5058)
- [x] `pages/common/nmap.md` (#5077)
- [x] `pages/common/tar.md` (#5078)
- [x] `pages/linux/yetris.md` (#5079)
- [x] `pages/osx/brew.md` (#5066)
- [x] `pages/windows/shutdown.md` (#5076)

**Comment by owenvoke** [comment]
We may also need to check any of the translations that exist for these pages, to ensure that they follow the updates (although we can't run the linter against them).

**Comment by waldyrious** [comment]
> We currently can't update as we need to clean up some of the pages.

@owenvoke so maybe this PR should be kept in draft status until then, right?

**Comment by bl-ue** [comment]
@owenvoke all of the 9-example pages are trimmed to 8! Go ahead and procede!
