### ISSUE TITLE
Let's document: tj/git-extras

### ISSUE THREAD

**Issue by bl-ue** [tldr-pages/tldr#5137]
We should add the commands from [tj/git-extras](https://github.com/tj/git-extras) (73):

- [x] [`abort`](https://github.com/tj/git-extras/blob/main/Commands.md#git-abort) → #6243
- [x] [`alias`](https://github.com/tj/git-extras/blob/main/Commands.md#git-alias) → #5979
- [x] [`archive-file`](https://github.com/tj/git-extras/blob/main/Commands.md#git-archive-file) → #5960
- [x] [`authors`](https://github.com/tj/git-extras/blob/main/Commands.md#git-authors) → #5951
- [x] [`browse`](https://github.com/tj/git-extras/blob/main/Commands.md#git-browse) → #5959
- [x] [`browse-ci`](https://github.com/tj/git-extras/blob/main/Commands.md#git-browse-ci) → #8500
- [x] [`brv`](https://github.com/tj/git-extras/blob/main/Commands.md#git-brv) → #5966
- [x] [`bulk`](https://github.com/tj/git-extras/blob/main/Commands.md#git-bulk) → #8946
- [x] [`changelog`](https://github.com/tj/git-extras/blob/main/Commands.md#git-changelog) → #7359
- [x] [`clear-soft`](https://github.com/tj/git-extras/blob/main/Commands.md#git-clear-soft) → #6616 
- [x] [`clear`](https://github.com/tj/git-extras/blob/main/Commands.md#git-clear) → #6614
- [x] [`coauthor`](https://github.com/tj/git-extras/blob/main/Commands.md#git-coauthor) → #6878
- [x] [`commits-since`](https://github.com/tj/git-extras/blob/main/Commands.md#git-commits-since) → #5968
- [ ] [`continue`](https://github.com/tj/git-extras/blob/main/Commands.md#git-continue) →
- [x] [`contrib`](https://github.com/tj/git-extras/blob/main/Commands.md#git-contrib) → #6064
- [x] [`count`](https://github.com/tj/git-extras/blob/main/Commands.md#git-count) → #5970
- [x] [`cp`](https://github.com/tj/git-extras/blob/main/Commands.md#git-cp) → #5947
- [x] [`create-branch`](https://github.com/tj/git-extras/blob/main/Commands.md#git-create-branch) → #5982
- [x] [`delete-branch`](https://github.com/tj/git-extras/blob/main/Commands.md#git-delete-branch) → #6011
- [x] [`delete-merged-branches`](https://github.com/tj/git-extras/blob/main/Commands.md#git-delete-merged-branches) → https://github.com/tldr-pages/tldr/commit/bdaada468136f24f4f1d92b0fb78a4444a70945d
- [x] [`delete-squashed-branches`](https://github.com/tj/git-extras/blob/main/Commands.md#git-delete-squashed-branches) → #10988
- [x] [`delete-submodule`](https://github.com/tj/git-extras/blob/main/Commands.md#git-delete-submodule) → #8553
- [x] [`delete-tag`](https://github.com/tj/git-extras/blob/main/Commands.md#git-delete-tag) → #5948
- [x] [`delta`](https://github.com/tj/git-extras/blob/main/Commands.md#git-delta) → #6010
- [x] [`effort`](https://github.com/tj/git-extras/blob/main/Commands.md#git-effort) → #6002
- [x] [`extras`](https://github.com/tj/git-extras/blob/main/Commands.md#git-extras) → #6037
- [x] [`feature`](https://github.com/tj/git-extras/blob/main/Commands.md#git-feature) → #9470
- [x] [`force-clone`](https://github.com/tj/git-extras/blob/main/Commands.md#git-force-clone) → #8724 
- [x] [`fork`](https://github.com/tj/git-extras/blob/main/Commands.md#git-fork) → #6013
- [x] [`fresh-branch`](https://github.com/tj/git-extras/blob/main/Commands.md#git-fresh-branch) → #10972
- [ ] [`get`](https://github.com/tj/git-extras/blob/main/Commands.md#git-get) →
- [x] [`gh-pages`](https://github.com/tj/git-extras/blob/main/Commands.md#git-gh-pages) → #8787 
- [x] [`graft`](https://github.com/tj/git-extras/blob/main/Commands.md#git-graft) → #6034
- [x] [`guilt`](https://github.com/tj/git-extras/blob/main/Commands.md#git-guilt) → #10890
- [x] [`ignore-io`](https://github.com/tj/git-extras/blob/main/Commands.md#git-ignore-io) → #3978, #5908
- [x] [`ignore`](https://github.com/tj/git-extras/blob/main/Commands.md#git-ignore) → #3978, #5908
- [x] [`info`](https://github.com/tj/git-extras/blob/main/Commands.md#git-info) → #6058
- [x] [`local-commits`](https://github.com/tj/git-extras/blob/main/Commands.md#git-local-commits) → #5981
- [x] [`lock`](https://github.com/tj/git-extras/blob/main/Commands.md#git-lock) → #6756
- [x] [`locked`](https://github.com/tj/git-extras/blob/main/Commands.md#git-locked) → #7034
- [x] [`magic`](https://github.com/tj/git-extras/blob/main/Commands.md#git-magic) → #10889
- [x] [`merge-into`](https://github.com/tj/git-extras/blob/main/Commands.md#git-merge-into) → #9386
- [x] [`merge-repo`](https://github.com/tj/git-extras/blob/main/Commands.md#git-merge-repo) → #9386
- [x] [`missing`](https://github.com/tj/git-extras/blob/main/Commands.md#git-missing) → #6126
- [x] [`mr`](https://github.com/tj/git-extras/blob/main/Commands.md#git-mr) → #7585 
- [x] [`obliterate`](https://github.com/tj/git-extras/blob/main/Commands.md#git-obliterate) → #6099
- [x] [`paste`](https://github.com/tj/git-extras/blob/main/Commands.md#git-paste) → #10992
- [x] [`pr`](https://github.com/tj/git-extras/blob/main/Commands.md#git-pr) → #2674
- [x] [`psykorebase`](https://github.com/tj/git-extras/blob/main/Commands.md#git-psykorebase) → #10994
- [x] [`pull-request`](https://github.com/tj/git-extras/blob/main/Commands.md#git-pull-request) → #10993
- [x] [`reauthor`](https://github.com/tj/git-extras/blob/main/Commands.md#git-reauthor) → #6651
- [x] [`rebase-patch`](https://github.com/tj/git-extras/blob/main/Commands.md#git-rebase-patch) → #10995
- [x] [`release`](https://github.com/tj/git-extras/blob/main/Commands.md#git-release) → #6095
- [x] [`rename-branch`](https://github.com/tj/git-extras/blob/main/Commands.md#git-rename-branch) → #5950
- [ ] [`rename-file`](https://github.com/tj/git-extras/blob/main/Commands.md#git-rename-file) →
- [x] [`rename-remote`](https://github.com/tj/git-extras/blob/main/Commands.md#git-rename-remote) → #6138
- [x] [`rename-tag`](https://github.com/tj/git-extras/blob/main/Commands.md#git-rename-tag) → #6092
- [x] [`repl`](https://github.com/tj/git-extras/blob/main/Commands.md#git-repl) → #5974
- [x] [`reset-file`](https://github.com/tj/git-extras/blob/main/Commands.md#git-reset-file) → #6003
- [x] [`root`](https://github.com/tj/git-extras/blob/main/Commands.md#git-root) → #6009
- [x] [`rscp`](https://github.com/tj/git-extras/blob/main/Commands.md#git-rscp) → #10996
- [x] [`scp`](https://github.com/tj/git-extras/blob/main/Commands.md#git-scp) → #9385
- [x] [`sed`](https://github.com/tj/git-extras/blob/main/Commands.md#git-sed) → #7356
- [x] [`setup`](https://github.com/tj/git-extras/blob/main/Commands.md#git-setup) → #6057
- [x] [`show-merged-branches`](https://github.com/tj/git-extras/blob/main/Commands.md#git-show-merged-branches) → #8048
- [x] [`show-tree`](https://github.com/tj/git-extras/blob/main/Commands.md#git-show-tree) → #6164
- [x] [`show-unmerged-branches`](https://github.com/tj/git-extras/blob/main/Commands.md#git-show-unmerged-branches) → #8049
- [x] [`squash`](https://github.com/tj/git-extras/blob/main/Commands.md#git-squash) → #7361
- [x] [`stamp`](https://github.com/tj/git-extras/blob/main/Commands.md#git-stamp) → #8730 
- [x] [`standup`](https://github.com/tj/git-extras/blob/main/Commands.md#git-standup) → #7584 
- [x] [`summary`](https://github.com/tj/git-extras/blob/main/Commands.md#git-summary) → #6065
- [x] [`sync`](https://github.com/tj/git-extras/blob/main/Commands.md#git-sync) → #7357 
- [x] [`touch`](https://github.com/tj/git-extras/blob/main/Commands.md#git-touch) → #6015
- [x] [`undo`](https://github.com/tj/git-extras/blob/main/Commands.md#git-undo) → #5980
- [x] [`unlock`](https://github.com/tj/git-extras/blob/main/Commands.md#git-unlock) → #7035
- [x] [`utimes`](https://github.com/tj/git-extras/blob/main/Commands.md#git-utimes) → #8729
- [ ] [`unwip`](https://github.com/tj/git-extras/blob/main/Commands.md#git-unwip) →
- [ ] [`wip`](https://github.com/tj/git-extras/blob/main/Commands.md#git-wip) →

**Comment by sbrl** [comment]
Is there any overlap with #3953? if so, we should edit #3953 and move the relevant ones over here.

**Comment by bl-ue** [comment]
@sbrl no.  I added the commands copied directly from [the git-extras readme](https://github.com/tj/git-extras) into #3953, but then per @waldyrious's suggestion moved them here.

**Comment by waldyrious** [comment]
I'm not sure this was made clear before, but might want to come to an agreement about whether to document these as top-level commands (e.g. `git-ignore.md`) or subcommands of `git-extras` (e.g. `git-extras-ignore.md`). I'm concerned that there may be a lot of overlap of command names with similar git CLI helpers (some of which are [listed here](https://github.com/tldr-pages/tldr/issues/3953#issuecomment-758259123)), and we probably don't want to give priority to one of them, or worse, assign precedence on a first-come-first-served basis.

Pinging @CleanMachine1 as a heads-up, due to [this comment on Gitter](https://gitter.im/tldr-pages/tldr?at=609bc123f2c939630cdc37ab).

**Comment by CleanMachine1** [comment]
well to be honest, I didn't plan to do the ones which overlap, however what could be done, in the git included ones which overlap, maybe put a, see also in the desc

**Comment by waldyrious** [comment]
To be clear, I meant overlap with other git CLI helpers (which may use the same subcommand names), not just with git itself.

**Comment by CleanMachine1** [comment]
OK, what do you suggest?

**Comment by bl-ue** [comment]
I don't think that `git-extras-<command>.md` is very good because I doubt anyone would every think to try `tldr git extras <command>`, the reason for that being that `git extras` and `git extras <command>` simply show the `git-extras` man page, and don't actually execute and commands 🤔

**Comment by patricedenis** [comment]
yes. I think the same way.
I think it's better to keep the name of the tldr commands as near as the invocation the users will tape.

**Comment by CleanMachine1** [comment]
Since there is no autofill with tldr, I agree that it is better to keep it similar to what the user will type for their actual command.

**Comment by marchersimon** [comment]
How does the system prioritize them? When you execute a git subcommand which is also a git-extras subcommand, somehow the shell has to figure out which one to use.

**Comment by CleanMachine1** [comment]
Why have you closed?

**Comment by CleanMachine1** [comment]
@marchersimon

**Comment by marchersimon** [comment]
@patricedenis linked this issue with #5948 and when I merged it it was closed.

**Comment by CleanMachine1** [comment]
Ok, just thought we were going to discontinue support git-extras, I plan on doing more maybe tomorrow

**Comment by bl-ue** [comment]
Yep, definitely not intended.

**Comment by sbrl** [comment]
Generally speaking in our case, documenting extra subcommands that are part of an addon is fine (though I recommend mentioning that they are part of an external program or something in the description), but we do not want to overwrite any pre-existing core git commands - those should be prioritised over anything provided by a third party extension.

**Comment by sebastiaanspeck** [comment]
`rscp` is a symlink for `scp`. Do we add pages for symlinks?

**Comment by kbdharun** [comment]
> `rscp` is a symlink for `scp`. Do we add pages for symlinks?

In that case, we could add it as an [alias page](https://github.com/tldr-pages/tldr/blob/main/contributing-guides/translation-templates/alias-pages.md#en)

**Comment by sebastiaanspeck** [comment]
Like this? https://github.com/tldr-pages/tldr/pull/10996

**Comment by sebastiaanspeck** [comment]
fresh-branch is merged, but not ticked

**Comment by kbdharun** [comment]
> fresh-branch is merged, but not ticked

On it, will update it for the other open PRs too.

**Comment by sebastiaanspeck** [comment]
> > fresh-branch is merged, but not ticked
> 
> On it, will update it for the other open PRs too.

Great! Missed one: https://github.com/tldr-pages/tldr/pull/10995

**Comment by sebastiaanspeck** [comment]
All open PR's are merged, so we can complete this issue! 🚀

**Comment by sebastiaanspeck** [comment]
Maybe unpin this one since it is closed?

**Comment by dmmqz** [comment]
I have added 5 commands that were missing (`continue`, `get`, `rename-file`, `unwip`, and `wip`).
