### ISSUE TITLE
Epic: Add links to all existing pages

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr#5510]
Since #2649, tldr pages support adding a link to the tool's homepage, and [substantial efforts to backfill links into existing pages](https://github.com/tldr-pages/tldr/pulls?q=is%3Apr+sort%3Aupdated-desc+multiple+pages%3A+add+homepages+is%3Aclosed) have been made, but many are still lacking it.

We should ensure that all pages have a link that people can follow to learn more about the tool and explore more comprehensive documentation. Pages of projects that don't have a dedicated web page should either link to their parent project's page, or we should come up with a way to explicitly indicate that they don't have a homepage.

(Note: This should be done with a separate PR for each page (or at best, multi-page PRs for related sets of pages, such as all the subcommands of a given command), so that discussion about which links to use for some pages won't block the straightforward changes to the other pages.)

Once that work is completed, we should add a check to [tldr-lint](https://github.com/tldr-pages/tldr-lint) to make this field required, thus ensuring that new pages won't regress our coverage in that regard (see #5046 for examples of link-related checks that were incorporated into tldr-lint). We should also change the template for a page in `CONTRIBUTING.md`, the style guide, and other places where that may be relevant.

**Comment by navarroaxel** [comment]
Question: What we should do with pages like https://github.com/tldr-pages/tldr/blob/master/pages/linux/ksvgtopng5.md? This is an internal command/util from the KDE Plasma desktop and doesn't have a man page. Should we use the link to the git repository?

**Comment by bl-ue** [comment]
I'd say the Git repository for that tool (or group of related tools), or the parent project's page (e.g. the KDE Plasma Desktop's page).  We link to Git repos (e.g. [GitHub](https://github.com/tldr-pages/tldr/search?q=more+information+github.com), [GitLab](https://github.com/tldr-pages/tldr/search?q=more+information+gitlab.com)) a lot.

**Comment by marchersimon** [comment]
- [ ] android/settings
- [ ] android/cmd
- [ ] common/fortune
- [ ] common/ed
- [ ] common/where
- [ ] common/calendar
- [ ] common/sed
- [ ] common/for
- [ ] common/banner
- [ ] common/sha512sum
- [ ] common/nl
- [ ] common/jhat
- [ ] common/cd
- [ ] common/fmt
- [ ] common/batch
- [ ] common/waitress-serve
- [ ] common/echo
- [ ] common/mkfifo
- [ ] common/cmp
- [ ] common/ldapsearch
- [ ] common/ssh-copy-id
- [ ] common/entr
- [ ] common/most
- [ ] common/shasum
- [ ] common/cksum
- [ ] common/users
- [ ] common/tee
- [ ] common/odps-tunnel
- [ ] common/wasm-objdump
- [ ] common/rbash
- [ ] common/unar
- [ ] common/clear
- [ ] common/pdfjoin
- [ ] common/route
- [ ] common/stat
- [ ] common/join
- [ ] common/pdftotext
- [ ] common/rabin2
- [ ] common/rsync
- [ ] common/s
- [ ] common/complete
- [ ] common/mmv
- [ ] common/dirs
- [ ] common/mv
- [ ] common/jstack
- [ ] common/write
- [ ] common/ssh
- [ ] common/more
- [ ] common/ifconfig
- [ ] common/dhclient
- [ ] common/xmllint
- [ ] common/leave
- [ ] common/airpaste
- [ ] common/traceroute
- [ ] common/wasm2wat
- [ ] common/umask
- [ ] common/uniq
- [ ] common/javac
- [ ] common/du
- [ ] common/tty
- [ ] common/virt-sparsify
- [ ] common/pax
- [ ] common/nohup
- [ ] common/task
- [ ] common/ssh-agent
- [ ] common/timeout
- [ ] common/sd
- [ ] common/transcode
- [ ] common/odps-func
- [ ] common/pv
- [ ] common/seq
- [ ] common/sha384sum
- [ ] common/meshlabserver
- [ ] common/flex
- [ ] common/factor
- [ ] common/odps-inst
- [ ] common/sha1sum
- [ ] common/passwd
- [ ] common/renice
- [ ] common/base32
- [ ] common/cut
- [ ] common/ionice
- [ ] common/split
- [ ] common/zpool
- [ ] common/id
- [ ] common/shc
- [ ] common/mscore
- [ ] common/killall
- [ ] common/shopt
- [ ] common/tac
- [ ] common/telnet
- [ ] common/monop
- [ ] common/odps
- [ ] common/ar
- [ ] common/drill
- [ ] common/lpstat
- [ ] common/rev
- [ ] common/hostid
- [ ] common/qemu-img
- [ ] common/envsubst
- [ ] common/ping6
- [ ] common/wpa_supplicant
- [ ] common/link
- [ ] common/expr
- [ ] common/less
- [ ] common/dircolors
- [ ] common/odps-auth
- [ ] common/last
- [ ] common/head
- [ ] common/unzip
- [ ] common/zless
- [ ] common/unalias
- [ ] common/jmap
- [ ] common/atq
- [ ] common/sync
- [ ] common/sha256sum
- [ ] common/shuf
- [ ] common/find
- [ ] common/chcon
- [ ] common/ssh-keygen
- [ ] common/base64
- [ ] common/if
- [ ] common/zip
- [ ] common/apg
- [ ] common/time
- [ ] common/exec
- [ ] common/stty
- [ ] common/nslookup
- [ ] common/rmdir
- [ ] common/su
- [ ] common/sum
- [ ] common/sftp
- [ ] common/nkf
- [ ] common/gunzip
- [ ] common/alias
- [ ] common/objdump
- [ ] common/df
- [ ] common/hr
- [ ] common/visudo
- [ ] common/uptime
- [ ] common/finger
- [ ] common/view
- [ ] common/who
- [ ] common/mail
- [ ] common/fold
- [ ] common/arch
- [ ] common/false
- [ ] common/script
- [ ] common/gpg-zip
- [ ] common/crontab
- [ ] common/c99
- [ ] common/groups
- [ ] common/od
- [ ] common/xephyr
- [ ] common/unclutter
- [ ] common/pactl
- [ ] common/vdir
- [ ] common/ps
- [ ] common/w
- [ ] common/umount
- [ ] common/slimrb
- [ ] common/dot
- [ ] common/bg
- [ ] common/tsort
- [ ] common/tail
- [ ] common/type
- [ ] common/read
- [ ] common/sdiff
- [ ] common/ipcs
- [ ] common/sn
- [ ] common/atrm
- [ ] common/samtools
- [ ] common/singularity
- [ ] common/badblocks
- [ ] common/rails-db
- [ ] common/unrar
- [ ] common/nice
- [ ] common/dirname
- [ ] common/xargs
- [ ] common/id3tag
- [ ] common/git-bugreport
- [ ] common/chsh
- [ ] common/set
- [ ] common/exit
- [ ] common/swig
- [ ] common/import
- [ ] common/fg
- [ ] common/lex
- [ ] common/jps
- [ ] common/cp
- [ ] common/sh
- [ ] common/pinky
- [ ] common/printf
- [ ] common/zfs
- [ ] common/ln
- [ ] common/diffstat
- [ ] common/chroot
- [ ] common/obs
- [ ] common/gzip
- [ ] common/uname
- [ ] common/iconv
- [ ] common/apropos
- [ ] common/mount
- [ ] common/md5sum
- [ ] common/yes
- [ ] common/odps-resource
- [ ] common/bc
- [ ] common/readlink
- [ ] common/wasm2c
- [ ] common/wait
- [ ] common/comm
- [ ] common/ping
- [ ] common/unlink
- [ ] common/spatial
- [ ] common/chown
- [ ] common/command
- [ ] common/roll
- [ ] common/strings
- [ ] common/case
- [ ] common/dc
- [ ] common/which
- [ ] common/ulimit
- [ ] common/ssh-keyscan
- [ ] common/host
- [ ] common/fgrep
- [ ] common/tput
- [ ] common/pssh
- [ ] common/socat
- [ ] common/wasm-opt
- [ ] common/true
- [ ] common/logname
- [ ] common/htop
- [ ] common/ls
- [ ] common/pygmentize
- [ ] common/pwd
- [ ] common/shred
- [ ] common/ftp
- [ ] common/zcat
- [ ] common/tldrl
- [ ] common/sha224sum
- [ ] common/source
- [ ] common/screen
- [ ] common/sshpass
- [ ] common/ufraw-batch
- [ ] common/history
- [ ] common/lp
- [ ] common/glib-compile-resources
- [ ] common/xkill
- [ ] common/stdbuf
- [ ] common/env
- [ ] common/lsof
- [ ] common/realpath
- [ ] common/platformio
- [ ] common/wc
- [ ] common/jobs
- [ ] common/while
- [ ] common/paci
- [ ] common/lorem
- [ ] common/quota
- [ ] common/sleep
- [ ] common/pathchk
- [ ] common/mailx
- [ ] common/sendmail
- [ ] common/whoami
- [ ] common/kill
- [ ] common/tr
- [ ] common/rm
- [ ] common/zdb
- [ ] common/watch
- [ ] common/figlet
- [ ] common/mesg
- [ ] common/nproc
- [ ] common/unexpand
- [ ] common/arp
- [ ] common/truncate
- [ ] common/odps-table
- [ ] common/pdfimages
- [ ] common/install
- [ ] common/printenv
- [ ] common/expand
- [ ] common/chgrp
- [ ] common/vimtutor
- [ ] common/date
- [ ] common/column
- [ ] common/rar
- [ ] common/xxd
- [ ] common/paste
- [ ] common/patch
- [ ] linux/ebuild
- [ ] linux/lslocks
- [ ] linux/manpath
- [ ] linux/groupadd
- [ ] linux/ipcmk
- [ ] linux/snap
- [ ] linux/shutdown
- [ ] linux/ctrlaltdel
- [ ] linux/getfacl
- [ ] linux/mkfs
- [ ] linux/phar
- [ ] linux/lsblk
- [ ] linux/pdfgrep
- [ ] linux/cpufreq-set
- [ ] linux/aspell
- [ ] linux/sysctl
- [ ] linux/chage
- [ ] linux/gedit
- [ ] linux/diff3
- [ ] linux/chattr
- [ ] linux/quotacheck
- [ ] linux/ncdu
- [ ] linux/rpcinfo
- [ ] linux/lsusb
- [ ] linux/lrzip
- [ ] linux/guix-package
- [ ] linux/hwclock
- [ ] linux/ncat
- [ ] linux/paccache
- [ ] linux/namei
- [ ] linux/lastlog
- [ ] linux/resize2fs
- [ ] linux/isoinfo
- [ ] linux/ntfsfix
- [ ] linux/datamash
- [ ] linux/x11vnc
- [ ] linux/usermod
- [ ] linux/login
- [ ] linux/addr2line
- [ ] linux/kpartx
- [ ] linux/eval
- [ ] linux/fstrim
- [ ] linux/wodim
- [ ] linux/pstree
- [ ] linux/file
- [ ] linux/uprecords
- [ ] linux/n
- [ ] linux/lsmod
- [ ] linux/prename
- [ ] linux/hostnamectl
- [ ] linux/rtcwake
- [ ] linux/mkswap
- [ ] linux/mkfs.fat
- [ ] linux/apt-file
- [ ] linux/sar
- [ ] linux/kde-inhibit
- [ ] linux/genkernel
- [ ] linux/cpufreq-aperf
- [ ] linux/vpnc
- [ ] linux/top
- [ ] linux/chfn
- [ ] linux/sshuttle
- [ ] linux/pkgrm
- [ ] linux/useradd
- [ ] linux/runsv
- [ ] linux/firejail
- [ ] linux/pkginfo
- [ ] linux/wpa_passphrase
- [ ] linux/systemd-analyze
- [ ] linux/wpa_cli
- [ ] linux/viewnior
- [ ] linux/runsvdir
- [ ] linux/ldd
- [ ] linux/apt-mark
- [ ] linux/edit
- [ ] linux/iostat
- [ ] linux/xfce4-screenshooter
- [ ] linux/hdparm
- [ ] linux/whatis
- [ ] linux/gpasswd
- [ ] linux/setxkbmap
- [ ] linux/fdisk
- [ ] linux/mpstat
- [ ] linux/runuser
- [ ] linux/brew
- [ ] linux/ac
- [ ] linux/cmus
- [ ] linux/feh
- [ ] linux/pkgmk
- [ ] linux/apt-cache
- [ ] linux/lrzuntar
- [ ] linux/pacaur
- [ ] linux/export
- [ ] linux/ndctl
- [ ] linux/journalctl
- [ ] linux/btrfs
- [ ] linux/rtorrent
- [ ] linux/timedatectl
- [ ] linux/compgen
- [ ] linux/apt-add-repository
- [ ] linux/apache2ctl
- [ ] linux/nmon
- [ ] linux/dbus-daemon
- [ ] linux/light
- [ ] linux/trap
- [ ] linux/whiptail
- [ ] linux/zenity
- [ ] linux/logwatch
- [ ] linux/authconfig
- [ ] linux/apt-get
- [ ] linux/inxi
- [ ] linux/debman
- [ ] linux/xsel
- [ ] linux/free
- [ ] linux/scriptreplay
- [ ] linux/imgp
- [ ] linux/mknod
- [ ] linux/rc-status
- [ ] linux/kexec
- [ ] linux/xeyes
- [ ] linux/cpufreq-info
- [ ] linux/smbpasswd
- [ ] linux/rspamc
- [ ] linux/brctl
- [ ] linux/pwgen
- [ ] linux/nologin
- [ ] linux/pamac
- [ ] linux/vncserver
- [ ] linux/logger
- [ ] linux/service
- [ ] linux/dos2unix
- [ ] linux/at
- [ ] linux/unix2mac
- [ ] linux/vmware-checkvm
- [ ] linux/arp-scan
- [ ] linux/xar
- [ ] linux/strace
- [ ] linux/mssh
- [ ] linux/do-release-upgrade
- [ ] linux/fc-match
- [ ] linux/prt-get
- [ ] linux/hostname
- [ ] linux/apt
- [ ] linux/foreman
- [ ] linux/lxc
- [ ] linux/blkdiscard
- [ ] linux/xsetwacom
- [ ] linux/see
- [ ] linux/mimetype
- [ ] linux/mkfs.minix
- [ ] linux/f5fpc
- [ ] linux/hardinfo
- [ ] linux/reset
- [ ] linux/apk
- [ ] linux/tlp-stat
- [ ] linux/notify-send
- [ ] linux/httpie
- [ ] linux/pulseaudio
- [ ] linux/pushd
- [ ] linux/popd
- [ ] linux/terminator
- [ ] linux/cryptsetup
- [ ] linux/beep
- [ ] linux/ksvgtopng5
- [ ] linux/bmon
- [ ] linux/xclock
- [ ] linux/sensors
- [ ] linux/xdotool
- [ ] linux/fc-cache
- [ ] linux/csplit
- [ ] linux/blkid
- [ ] linux/betterlockscreen
- [ ] linux/nmtui
- [ ] linux/getent
- [ ] linux/nft
- [ ] linux/enum4- [ ] linux
- [ ] linux/pasuspender
- [ ] linux/phpquery
- [ ] linux/slapt-get
- [ ] linux/xfce4-terminal
- [ ] linux/modinfo
- [ ] linux/as
- [ ] linux/urxvt
- [ ] linux/medusa
- [ ] linux/lsb_release
- [ ] linux/perf
- [ ] linux/rfkill
- [ ] linux/lshw
- [ ] linux/sensible-editor
- [ ] linux/lrztar
- [ ] linux/dunstify
- [ ] linux/mkfs.ext4
- [ ] linux/repquota
- [ ] linux/calc
- [ ] linux/squeue
- [ ] linux/eix
- [ ] linux/vncviewer
- [ ] linux/uuidgen
- [ ] linux/ul
- [ ] linux/script
- [ ] linux/newgrp
- [ ] linux/taskset
- [ ] linux/losetup
- [ ] linux/whereis
- [ ] linux/iw
- [ ] linux/sbatch
- [ ] linux/mycli
- [ ] linux/tomb
- [ ] linux/autorandr
- [ ] linux/zgrep
- [ ] linux/swapoff
- [ ] linux/reflector
- [ ] linux/e4defrag
- [ ] linux/tlp
- [ ] linux/xclip
- [ ] linux/fc-pattern
- [ ] linux/cpuid
- [ ] linux/tcpkill
- [ ] linux/yaourt
- [ ] linux/rename
- [ ] linux/dpkg-query
- [ ] linux/phpdismod
- [ ] linux/compose
- [ ] linux/dash
- [ ] linux/update-rc.d
- [ ] linux/guake
- [ ] linux/powertop
- [ ] linux/swapon
- [ ] linux/findmnt
- [ ] linux/rdesktop
- [ ] linux/mac2unix
- [ ] linux/unix2dos
- [ ] linux/e2label
- [ ] linux/mkfs.vfat
- [ ] linux/rc-update
- [ ] linux/ssh-add
- [ ] linux/http-prompt
- [ ] linux/groupmod
- [ ] linux/line
- [ ] linux/sv
- [ ] linux/eject
- [ ] linux/wipefs
- [ ] linux/disown
- [ ] linux/tune2fs
- [ ] linux/cp
- [ ] linux/archey
- [ ] linux/alpine
- [ ] linux/ports
- [ ] linux/modprobe
- [ ] linux/qsub
- [ ] linux/mkfs.exfat
- [ ] linux/dmesg
- [ ] linux/colrm
- [ ] linux/vnstat
- [ ] linux/pkgadd
- [ ] linux/groupdel
- [ ] linux/fc
- [ ] linux/pwdx
- [ ] linux/yank
- [ ] linux/edquota
- [ ] linux/perl-rename
- [ ] linux/rpm
- [ ] linux/nm
- [ ] linux/macchanger
- [ ] linux/setfacl
- [ ] linux/adduser
- [ ] linux/locate
- [ ] linux/microcom
- [ ] linux/fsck
- [ ] linux/xtrlock
- [ ] linux/chcpu
- [ ] linux/xinput
- [ ] linux/firewall-cmd
- [ ] linux/inotifywait
- [ ] linux/mountpoint
- [ ] linux/xrandr
- [ ] linux/uvcdynctrl
- [ ] linux/lsscsi
- [ ] linux/phpenmod
- [ ] linux/opkg
- [ ] linux/lsattr
- [ ] linux/ss
- [ ] linux/smbclient
- [ ] linux/runit
- [ ] linux/hexdump
- [ ] linux/mke2fs
- [ ] linux/unset
- [ ] linux/update-alternatives
- [ ] linux/tshark
- [ ] linux/gnome-terminal
- [ ] linux/pidof
- [ ] linux/bluetoothctl
- [ ] linux/file-rename
- [ ] linux/add-apt-repository
- [ ] linux/equery
- [ ] linux/lldb
- [ ] linux/apt-key
- [ ] linux/fcrackzip
- [ ] linux/pidstat
- [ ] linux/rc-service
- [ ] linux/ipcalc
- [ ] linux/ip-address
- [ ] linux/jobs
- [ ] linux/ufw
- [ ] linux/ptx
- [ ] linux/lspci
- [ ] linux/debugfs
- [ ] linux/emerge
- [ ] linux/zramctl
- [ ] linux/wall
- [ ] linux/print
- [ ] linux/sensible-browser
- [ ] linux/scrot
- [ ] linux/zypper
- [ ] linux/fc-list
- [ ] linux/updatedb
- [ ] linux/xterm
- [ ] linux/trizen
- [ ] linux/sa
- [ ] linux/run-mailcap
- [ ] linux/runcon
- [ ] linux/fatlabel
- [ ] linux/lrunzip
- [ ] linux/fallocate
- [ ] linux/i7z
- [ ] linux/stress
- [ ] linux/create_ap
- [ ] linux/mkisofs
- [ ] linux/mkfs.cramfs
- [ ] linux/chkconfig
- [ ] linux/amixer
- [ ] linux/watch
- [ ] linux/dmenu
- [ ] linux/mkfs.ntfs
- [ ] linux/mcookie
- [ ] linux/e2fsck
- [ ] linux/flatpak
- [ ] linux/lastb
- [ ] linux/wmctrl
- [ ] linux/dmidecode
- [ ] linux/cal
- [ ] linux/ldconfig
- [ ] linux/xman
- [ ] linux/aptitude
- [ ] linux/fuser
- [ ] linux/ipcrm
- [ ] linux/gs
- [ ] linux/lscpu
- [ ] linux/utmpdump
- [ ] linux/tcpflow
- [ ] osx/mdutil
- [ ] osx/sed
- [ ] osx/shutdown
- [ ] osx/pdfgrep
- [ ] osx/plutil
- [ ] osx/sysctl
- [ ] osx/networksetup
- [ ] osx/say
- [ ] osx/softwareupdate
- [ ] osx/eval
- [ ] osx/file
- [ ] osx/n
- [ ] osx/route
- [ ] osx/pkgutil
- [ ] osx/stat
- [ ] osx/top
- [ ] osx/chflags
- [ ] osx/sips
- [ ] osx/runsv
- [ ] osx/duti
- [ ] osx/du
- [ ] osx/ditto
- [ ] osx/runsvdir
- [ ] osx/rubocop
- [ ] osx/feh
- [ ] osx/hdiutil
- [ ] osx/export
- [ ] osx/safeejectgpu
- [ ] osx/compgen
- [ ] osx/mkfile
- [ ] osx/trap
- [ ] osx/xcode-select
- [ ] osx/split
- [ ] osx/dd
- [ ] osx/xed
- [ ] osx/pwgen
- [ ] osx/osascript
- [ ] osx/logger
- [ ] osx/qlmanage
- [ ] osx/screencapture
- [ ] osx/m
- [ ] osx/head
- [ ] osx/hostname
- [ ] osx/brightness
- [ ] osx/shuf
- [ ] osx/whence
- [ ] osx/xip
- [ ] osx/pushd
- [ ] osx/popd
- [ ] osx/base64
- [ ] osx/mdls
- [ ] osx/textutil
- [ ] osx/fdesetup
- [ ] osx/launchctl
- [ ] osx/as
- [ ] osx/uptime
- [ ] osx/look
- [ ] osx/port
- [ ] osx/diskutil
- [ ] osx/arch
- [ ] osx/whereis
- [ ] osx/xcodebuild
- [ ] osx/sw_vers
- [ ] osx/md5
- [ ] osx/xsltproc
- [ ] osx/w
- [ ] osx/reboot
- [ ] osx/imgcat
- [ ] osx/runsvchdir
- [ ] osx/systemsetup
- [ ] osx/rename
- [ ] osx/open
- [ ] osx/opensnoop
- [ ] osx/ssh-add
- [ ] osx/codesign
- [ ] osx/sv
- [ ] osx/units
- [ ] osx/system_profiler
- [ ] osx/scutil
- [ ] osx/archey
- [ ] osx/xattr
- [ ] osx/dmesg
- [ ] osx/mdfind
- [ ] osx/uname
- [ ] osx/oathtool
- [ ] osx/fc
- [ ] osx/yank
- [ ] osx/nm
- [ ] osx/ping
- [ ] osx/locate
- [ ] osx/apachectl
- [ ] osx/fsck
- [ ] osx/carthage
- [ ] osx/runit
- [ ] osx/afinfo
- [ ] osx/hexdump
- [ ] osx/asr
- [ ] osx/airport
- [ ] osx/pmset
- [ ] osx/drutil
- [ ] osx/caffeinate
- [ ] osx/lldb
- [ ] osx/yaa
- [ ] osx/pbpaste
- [ ] osx/pod
- [ ] osx/getfileinfo
- [ ] osx/pbcopy
- [ ] osx/cal
- [ ] osx/date
- [ ] osx/afplay
- [ ] sunos/runsv
- [ ] sunos/runsvdir
- [ ] sunos/svcs
- [ ] sunos/snoop
- [ ] sunos/svccfg
- [ ] sunos/runsvchdir
- [ ] sunos/prctl
- [ ] sunos/sv
- [ ] sunos/dmesg
- [ ] sunos/svcadm
- [ ] sunos/runit
- [ ] sunos/truss
- [ ] sunos/devfsadm
- [ ] sunos/prstat
- [ ] windows/iscc
- [ ] windows/units
- [ ] windows/explorer
- [ ] windows/sigverif

**Comment by marchersimon** [comment]
I'm not sure if this was a good idea though...

**Comment by bl-ue** [comment]
Yeah, that's a crazily long list 😂

@marchersimon I'd open PRs fixing pages in batches of 10 or so, to reduce the PR count given these are simple changes.

**Comment by marchersimon** [comment]
@bl-ue what about @waldyrious's suggestion?
> (Note: This should be done with a separate PR for each page (or at best, multi-page PRs for related sets of pages, such as all the subcommands of a given command), so that discussion about which links to use for some pages won't block the straightforward changes to the other pages.)

**Comment by bl-ue** [comment]
I'm fine with that, the only thing I'm not sure about of is opening a bunch of PRs that each add one line to one file...I'm not sure if that's a great idea.  But if that's okay with @waldyrious it's okay with me.

**Comment by waldyrious** [comment]
If multiple PRs are adding links to the same site, or add links to pages that are related to each other, then by all means, it makes more sense to group those changes into a single PR.

Other than that, I don't see any problems with having lots of small PRs that are indeed unrelated to each other. Simple PRs are easy to review, and allow a fast turnaround, which is good both for maintainers and contributors alike.

**Comment by tomadojuice** [comment]
For the GNU coreutils (cd, mv, ...) should we add the link to the respective page on gnu.org? Example [https://www.gnu.org/software/coreutils/manual/html_node/mv-invocation.html](https://www.gnu.org/software/coreutils/manual/html_node/mv-invocation.html) for mv.

**Comment by bl-ue** [comment]
Yes definitely.  Those pages are very informative.

**Comment by marchersimon** [comment]
Should we also change the links of the current coreutils? (`chmod, dd, dir, mkdir, touch, b2sum, cat, basename`)

**Comment by tomadojuice** [comment]
@marchersimon It's certainly helpful but then again you could just look it up in the man page.

**Comment by bl-ue** [comment]
If they're man7.org ones I think we should move them to the gnu pages. I like those ones better; they're official and informative (and a contrast to man7.org that's all over tons of pages)

**Comment by bl-ue** [comment]
@marchersimon that's a really nice table you've made up there, but there's one problem with that you couldn't have avoided: in French, a special thin, unbreakable space is used before most punctution including colons, but it's hard (if not impossible) to copy the French space from the GitHub UI, so you might need to get it manually.

It's code `160` (`0xa0`, → ` `), and the best way to get it is to open your browser's JavaScript console and enter `String.fromCharCode(0xa0)`, and then copy the resulting character within the quotes.

**Comment by marchersimon** [comment]
@bl-ue could I also add a note that it should be copied from another french page?

**Comment by bl-ue** [comment]
Certainly @marchersimon please feel free and you don't need to ask 👍🏻

**Comment by bl-ue** [comment]
@marchersimon try this for changing/adding links: https://gist.github.com/bl-ue/5b52c9f80dd21074c0633a2bcdeb01fb

Usage:
```bash
export TLDR_ROOT="path/to/tldr_directory"  # run this once per terminal session
python3 set_more_info_link.py -p common/chmod "https://url......."   # omit the .md extension
```

**Comment by marchersimon** [comment]
This is really cool, thanks!

**Comment by bl-ue** [comment]
Hey @marchersimon can you wait for a second before updating that comment? I'm trying to add some stuff 🙂

**Comment by marchersimon** [comment]
Did you remove the section or did I mess something up? Because I can't revert it

**Comment by bl-ue** [comment]
You removed the sections (according to GH).  We both hit "update comment" at the exact same time :D

**Comment by bl-ue** [comment]
I like it better without the letter grouping, so will you please leave it all open?  It's easier to find items, I think.

**Comment by waldyrious** [comment]
@marchersimon just to be clear, when I said

> If multiple PRs are adding links to the same site (...) it makes more sense to group those changes into a single PR.

...I had in mind precisely a case such as the GNU coreutils pages, which all follow the same pattern an link to the same base site. In that case, rather than opening one PR per page, it would be OK to have all changes in a single PR (even if you keep the changes to each page on its own commit in the PR branch). Can you do so for the remaining ones, please? And apply a similar logic to the updates to the other pages as well.

**Comment by bl-ue** [comment]
Related: #5111

**Comment by waldyrious** [comment]
Thanks for cross-linking the threads! I believe you may be referring to the following comments (please correct me if not):

@owenvoke:
> I have nothing against adding links from non-official sources (I'm all for adding more links that are useful). I just feel like it might lead to adding links that aren't particularly useful just because that's the only thing available.

@schneiderl 
> I don't think I like forcing to have a link for every page.
In some cases, there is no interesting link to be put on the description.
Also, in some cases, we might be just repeating ourselves (see #3041).

@sbrl:
> Adding links is nice, but it's not suitable for all commands. Take arch or nproc for example. I think this is best left out of the linter.

The conversation in #3041 which @schneiderl linked to (and which I've shamefully ended up never responding to until now (though in my defense GitHub started deleting notifications older than 6 months a while ago 😢)) also has some points against adding links when they may be considered redundant, mostly by @agnivade.

In all these cases, I believe what I suggested above can address those concerns:

> Pages of projects that don't have a dedicated web page should either link to their parent project's page, **or we should come up with a way to explicitly indicate that they don't have a homepage**.

I realize could have been more explicit there, but I didn't want to make the opening comment too verbose. What I had in mind was either a metadata file like what @srsudar [suggested](https://github.com/tldr-pages/tldr/issues/5299#issuecomment-798808923) for the aliases in #5299, or a special markup that we could add to the pages themselves. Something like this, for example:

```md
# foobar

> Description bla bla bla.
> More information: <N/A>.
```

**Comment by bl-ue** [comment]
Yes, those exactly were the comments I was thinking. 

I like the idea of using `N/A`—I think it would solve all the problems **without** requiring a spec revision / client update.

**Comment by waldyrious** [comment]
> Yes, those exactly were the comments I was thinking.

Next time I'd appreciate if you saved me the duplicated work, then 😅

**Comment by sbrl** [comment]
Yeah, finding a way to explicitly indicate that there isn't a suitable web page is a good idea. We can't use the angle-brackets (`<N/A>`) though, because in the [CommonMark spec that's the syntax for autolinks](https://spec.commonmark.org/0.29/#autolinks). Perhaps simply dropping the angle brackets and doing something like this would be better:

```markdown
> More information: N/A.
```

**Comment by bl-ue** [comment]
What about alias pages #5299?  Should we add links to them?

**Comment by marchersimon** [comment]
If we didn't, that would cause problems with `tldr-lint` as soon as we make them required. But we also can't use `<N/A>`, since that would be wrong.

**Comment by waldyrious** [comment]
I'd say we can adjust the logic of the linter to

1. ensure all alias pages follow the same format (like we do with the link labels, ensuring it spells exactly "More information:", etc.), and then
2. implement the upcoming rule that checks that a link (or `N/A`) is present in a way that ignores the alias pages (which should be easily identifiable if the point above is implemented).

**Comment by bl-ue** [comment]
👍🏻.  What if an alias has it's own particular page which documents the fact that it is an alias and links to the source command's page?

**Comment by waldyrious** [comment]
I don't understand what you mean. Are you suggesting to use the "More information" field in alias pages to link to the original pages, rather than the example format that was proposed in #5299?

**Comment by bl-ue** [comment]
Sorry, that wasn't very coherent 😛 

No, I was that an alias page should (must) have the exact same link as the source page.  For example, if `abc.md` has a link to `https://abc.com/`, then `def.md`, which is an alias page to `abc.md`, should have a link `https://abc.com/`.

**Comment by waldyrious** [comment]
That seems redundant and even noisy IMO. The alias page should be as short as possible and contain only the information needed to allow the user to find the correct page. In fact, I'm even thinking that we might want to use a more compact format, such as

```markdown
# foo

> Alias of `bar`.
```

(though this format is something to be discussed at #5299, not here).

**Comment by bl-ue** [comment]
About the link: I agree  About the compact format: so zero examples?  I'm not sure the linter would like that.

**Comment by waldyrious** [comment]
If the linter will have an exception for alias pages so it won't require a link in those cases, then it can just as well do the same for requiring examples.

**Comment by patricedenis** [comment]
Hi 
I was trying to add pinky.md but then I found that it was already included from Pull Request #2284 and commit #e4c03937386.
We may tick the case above, don't we?

**Comment by marchersimon** [comment]
Should I move my list to a seperate issue, so it's possible to scroll and discuss here and keep track of pages in the new issue?

**Comment by sbrl** [comment]
@marchersimon perhaps a good idea, since it is quite long haha

Have this as the meta discussion issue, and a new one as a tracking issue.

**Comment by marchersimon** [comment]
Done. I left out finished pages to avoid getting a notification for every PR which was linked in the list.

**Comment by marchersimon** [comment]
Should I also close this issue or is there something left to discuss?
