### ISSUE TITLE
Let’s document Glab Cli

### ISSUE THREAD

**Issue by antoine-amara** [tldr-pages/tldr#7554]
Glab CLI is the equivalent of Github CLI (GH) for Gitlab. TLDR already has documentation for the Glab command. Like GH, let's create some dedicated pages for Glab subcommands.

Find the main list of commands to document bellow and they’re equivalent in GH cli:
* [x] glab auth -- [gh auth](https://github.com/tldr-pages/tldr/blob/8ebd171d6f001698709fefc02b1fd5cc9f3a99c4/pages/common/gh-auth.md) -- https://github.com/tldr-pages/tldr/pull/7612
* [x] glab repo -- [gh repo](https://github.com/tldr-pages/tldr/blob/8ebd171d6f001698709fefc02b1fd5cc9f3a99c4/pages/common/gh-repo.md) -- https://github.com/tldr-pages/tldr/pull/7558
* [x] glab issue -- [gh issue](https://github.com/tldr-pages/tldr/blob/8ebd171d6f001698709fefc02b1fd5cc9f3a99c4/pages/common/gh-issue.md) -- https://github.com/tldr-pages/tldr/pull/7615
* [x] glab mr -- [gh pr](https://github.com/tldr-pages/tldr/blob/8ebd171d6f001698709fefc02b1fd5cc9f3a99c4/pages/common/gh-pr.md) -- https://github.com/tldr-pages/tldr/pull/7635
* [x] glab pipeline -- [gh workflow](https://github.com/tldr-pages/tldr/blob/5ff5ff69e266952d82fa2a69024b3f5b296e1eb3/pages/common/gh-workflow.md) -- #7642
* [x] glab release -- [gh release](https://github.com/tldr-pages/tldr/blob/8ebd171d6f001698709fefc02b1fd5cc9f3a99c4/pages/common/gh-release.md) -- #7643
* [x] glab alias -- [gh alias](https://github.com/tldr-pages/tldr/blob/3e4c519004a471c861cdc609fd7239ee3355671c/pages/common/gh-alias.md) -- #7641

Finally, a link to the Glab CLI documentation: [glab.readthedocs.io](https://glab.readthedocs.io/en/latest/)

> **Note**: be free to propose additional commands to document, I'll add them to the list.

**Comment by reinhart1010** [comment]
> Glab CLI is the equivalent of Github CLI (GH) for Gitlab

Is `glab` can be used as a drop-in replacement to `gh` (i.e. all documented commands and options are interoperable between `gh` and `glab`)? If so we can close this with a massive PR to copy `gh` subcommands to `glab`, translations included.

**Comment by reinhart1010** [comment]
Edit: Apparently it isn't a drop-in replacement, while the `gh` commands seem to have very few translations.
