### ISSUE TITLE
Let's document: Cockpit

### ISSUE THREAD

**Issue by kbdharun** [tldr-pages/tldr#9065]
### Command description

- The `Cockpit` is a web-based graphical interface for servers.
- It is a very famous tool which provides an accessible GUI for everyone to use.
- It works with many distros like Ubuntu, Fedora, etc. 
- It also comes with the default installation of the Fedora Server.

Reference: <https://cockpit-project.org>
Link to guide: <https://cockpit-project.org/guide/latest/>
Link to man pages: <https://cockpit-project.org/guide/latest/cockpit-manual.html>

## Commands

- [x] [cockpit-ws](https://cockpit-project.org/guide/latest/cockpit-ws.8.html) [Cockpit web service] → #9160
- [ ] [cockpit-desktop](https://cockpit-project.org/guide/latest/cockpit-desktop.1.html) [Cockpit Desktop integration] → #9145
- [ ] [cockpit-tls](https://cockpit-project.org/guide/latest/cockpit-tls.8.html) [TLS proxy for Cockpit web service] → #9145
- [ ] [cockpit-bridge](https://cockpit-project.org/guide/latest/cockpit-bridge.1.html) [Cockpit Host Bridge] → #9145

### OS

- ✅  Linux

**Comment by vatana7** [comment]
Assign me to this please!

**Comment by kbdharun** [comment]
> Assign me to this please!

@vatana7 Feel free to work on a PR for these commands. I don't think assigning is necessary. I assigned myself so that I could easily filter out Notifications in GitHub + I can create some pages if this issue was still open after a long time.

**Comment by ohyahgit** [comment]
I would like to help with this too.

**Comment by navarroaxel** [comment]
@ohyahgit awesome! just send the PR

**Comment by rajatmohan22** [comment]
Can you please provide the link where the commit needs to be done?

**Comment by kbdharun** [comment]
> Can you please provide the link where the .md file needs to be appended? Should it be added in /pages/common ?

No, As I mentioned this tool is for Linux so it must be placed in `pages/linux`.

**Comment by ohyahgit** [comment]
should I name the file for cockpit-ws cockpitws.md or cockpit-ws.md?

**Comment by ohyahgit** [comment]
I sent in a pull request for all four.

**Comment by ohyahgit** [comment]
I cannot figure out an error im getting on my pull request build

**Comment by kbdharun** [comment]
> I sent in a pull request for all four.

Great


> should I name the file for cockpit-ws `cockpitws.md` or `cockpit-ws.md`?

It must be named cockpit-ws.md, I will change it for you.

**Comment by ohyahgit** [comment]
Thank you! I just approved all your suggestions.
